baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Potisec" 
    subtitle = "Grupo de estudos sobre segurança da informação"
    keywords = "infosec, seguranca, informacao"
    copyright = ""
    menuMore = "Mostrar"
    writtenBy = "Escrito por"
    readMore = "Leia mais"
    readOtherPosts = "Leia outros posts"
    newerPosts = "Novos posts"
    olderPosts = "Posts passados"
    minuteReadingTime = "min de leitura"
    dateFormatSingle = "01-02-2006"
    dateFormatList = "02-01-2006"

    [languages.en.params.logo]
      logoText = "Potisec"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/pages/sobre"
      [[languages.en.menu.main]]
        identifier = "Blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "Agenda"
        name = "Agenda"
        url = "/meetup"
